<?
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

/*$data = '[
    {
      "id": "park_rocky-mountain2",
      "title": "Rocky Mountain",
      "description": "Bisected north to south by the Continental Divide, this portion of the Rockies has ecosystems varying from over 150 riparian lakes to montane and subalpine forests to treeless alpine tundra. Wildlife including mule deer, bighorn sheep, black bears, and cougars inhabit its igneous mountains and glacial valleys. Longs Peak, a classic Colorado fourteener, and the scenic Bear Lake are popular destinations, as well as the historic Trail Ridge Road, which reaches an elevation of more than 12,000 feet (3,700 m).",
      "nps_link": "https://www.nps.gov/romo/index.htm",
      "states": [
        "Colorado"
      ],
      "visitors": 4517585,
      "world_heritage_site": false,
      "location": "40.4,-105.58",
      "acres": 265795.2,
      "square_km": 1075.6,
      "date_established": "1915-01-26T06:00:00Z",
      "type":"test"
    }
  ]'; */
use app\models\Setting;
$url_appsearch =  $Setting = Setting::find()->where(['setting_name' => 'url_appsearch'])->one()->setting_value;

$data = json_encode($_POST['data']);

//echo (json_encode($data)); 
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $url_appsearch.'api/as/v1/engines/textxdb/documents');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $data );

$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Authorization: Bearer private-qxu2g6ochj2kve5ekpdvujoo';

curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}else echo 'success';
curl_close($ch);
?>
